used: true                                             # If the file has had data written to it
name: Player                                           # The user's selected name
health: 15                                             # The current health of the player
max_health: 15                                         # The maximum health the player can have
mana: 15                                               # The current mana of the player
max_mana: 15                                           # The maximum mana a player can have
level: 0                                               # The player's current level
skills:                                                # The skills of the player
  speed: 0
  agility: 0
  endurance: 0
  intelligence: 0
  charisma: 0
moves:                                                 # The moves the player can use
  check:
    target: !!python/name:ext.ext.Enemy ''
    range: !!python/object/apply:builtins.range
    - 0
    - 1
    - 1
    mana_required: 0
    custom_func: !!python/name:ext.ext.check_entity '' # A function that gets called when this move is used. Only special moves have this function
    description: Check enemy stats!
current_choice_code: ""                                # The current choice the user is on, this is stored as a string